collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2731872
color:
  saturation: 0.6568297
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#0C1717'
    - '#434943'
    - '#F4F3D1'
    - '#888777'
    - '#064353'
  rhythmicContrast: 1
layout_spectrum: 0.3549747
name: Littlelookbook
